---
bsc_rpc: regex("^(https?|ftp)://(-\.)?([^\s/?\.#]+\.?)+(/[^\s]*)?$", 'URI')
wallet: regex('^0x[a-fA-F0-9]{40}$', 'ethereum address', required=False)
min_pool_size_bnb: num(min=0.0001)
max_price_impact: num(min=0.001, max=0.999)
monitor_interval: num(min=1)
update_messages: bool(required=False)
price_in_usd: bool(required=False)
charts: list(enum('poocoin', 'bogged', 'dexguru', 'dextools', 'dexscreener'), required=False)
secrets:
  bscscan_api_key: str(required=False)
  telegram_token: regex('[0-9]{9,}:[a-zA-Z0-9_-]{35}', 'telegram token')
  admin_chat_id: int(min=1)
  rpc_auth_user: str(required=False)
  rpc_auth_password: str(required=False)
